<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:eb="http://www.ebxml.org/namespaces/messageHeader"
				  xmlns:pd="http://www.booking.com/websvc"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                  xmlns:xsd1="http://www.opentravel.org/OTA/2003/05" >
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="built-ins/msg-header-2_0.xsd"/>
            <xsd:import namespace="http://www.opentravel.org/OTA/2003/05" schemaLocation="Operations/getItineraryInfoRQ.xsd"/>
			<xsd:import namespace="http://www.opentravel.org/OTA/2003/05" schemaLocation="Operations/getItineraryInfoRS.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getItineraryInfoInput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="body" element="xsd1:getItineraryInfoRQ"/>
	</wsdl:message>

	<wsdl:message name="getItineraryInfoOutput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="body" element="xsd1:getItineraryInfoRS"/>
	</wsdl:message>

	<wsdl:portType name="ItineraryPortType">
		<wsdl:operation name="getItineraryInfo">
			<wsdl:input message="pd:getItineraryInfoRQ"/>
			<wsdl:output message="pd:getItineraryInfoRS"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ItinerarySoapBinding" type="xsd1:ItineraryPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="getItineraryInfo">
			<soap:operation soapAction="http://www.booking.com/getItineraryInfo"/>
			<wsdl:input>
				<soap:header message="pd:getItineraryInfoInput" part="header" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="pd:getItineraryInfoOutput" part="header" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="ItineraryService">
		<wsdl:port binding="ItinerarySoapBinding" name="pd:ItineraryPortType">
			<soap:address location="https://www.booking.com"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>