<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:eb="http://www.ebxml.org/namespaces/messageHeader"
				  xmlns:pd="http://www.booking.com/websvc"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:xsd1="http://www.opentravel.org/OTA/2003/05" >
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="built-ins/msg-header-2_0.xsd"/>
            <xsd:import namespace="http://www.opentravel.org/OTA/2003/05" schemaLocation="Operations/CreatechargeRequest.xsd"/>
            <xsd:import namespace="http://www.opentravel.org/OTA/2003/05" schemaLocation="Operations/CreatechargeRespond.xsd"/>
        </xsd:schema>
	</wsdl:types>

    <wsdl:message name="ChargeInput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="body" element="xsd1:PromotionMKTRQ"/>
	</wsdl:message>

	<wsdl:message name="ChargeOutput">
		<wsdl:part name="header" element="eb:MessageHeader"/>
		<wsdl:part name="body" element="xsd1:PromotionMKTRS"/>
	</wsdl:message>

    <wsdl:portType name="CreateChargePortType">
		<wsdl:operation name="CreateChargeInfo">
			<wsdl:input message="pd:CreatechargeRequest"/>
			<wsdl:output message="pd:CreatechargeResponse"/>
		</wsdl:operation>
	</wsdl:portType>

    <wsdl:binding name="CreateChargeSoapBinding" type="CreateChargePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="PromotionMKTInfo">
			<soap:operation soapAction="http://www.booking.com/getFlightavailableInfo"/>
			<wsdl:input>
				<soap:header message="pd:ChargeInput" part="header" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="pd:ChargeOutput" part="header" use="literal"/>
				<soap:body parts="body" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="PaymentService">
		<wsdl:port binding="CreateChargeSoapBinding" name="pd:CreateChargePortType">
			<soap:address location="https://www.booking.com"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>